version: "3"

services:
  db:
    image: postgres
    env_file:
      - database.env
    ports:
      - "5433:5432"



  incrementer:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db


